--- #YAML:1.0
name:               Any-Renderer
version:            1.015_02
abstract:           Common API for modules that convert data structures into strings
author:
    - Kevin McGrath
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Find:        0
    File::Spec:        0
    Log::Trace:        0
    Test::Assertions:  0
resources:
    repository:  https://github.com/kmcgrath/Any-Renderer
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
